#include "Framebuffer.hpp"

// C++11 Only: Some uniform initlilization :)
LookupNames Framebuffer::AttachmentNames = {
   {GL_COLOR_ATTACHMENT0, "GL_COLOR_ATTACHMENT0"},
   {GL_COLOR_ATTACHMENT1, "GL_COLOR_ATTACHMENT1"},
   {GL_COLOR_ATTACHMENT2, "GL_COLOR_ATTACHMENT2"},
   {GL_COLOR_ATTACHMENT3, "GL_COLOR_ATTACHMENT3"},
   {GL_DEPTH_ATTACHMENT, "GL_DEPTH_ATTACHMENT"},
   {GL_STENCIL_ATTACHMENT, "GL_STENCIL_ATTACHMENT"},
   {GL_DEPTH_STENCIL_ATTACHMENT, "GL_DEPTH_STENCIL_ATTACHMENT"},
};

LookupNames Framebuffer::TargetNames = {
   {GL_FRAMEBUFFER, "GL_FRAMEBUFFER"}, 
   {GL_DRAW_FRAMEBUFFER, "GL_DRAW_FRAMEBUFFER"},
   {GL_READ_FRAMEBUFFER, "GL_READ_FRAMEBUFFER"}
};

LookupNames Framebuffer::StatusNames = {
   { GL_FRAMEBUFFER_COMPLETE, "GL_FRAMEBUFFER_COMPLETE" },
   { GL_FRAMEBUFFER_UNDEFINED, "GL_FRAMEBUFFER_UNDEFINED" },
   { GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT, "GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT" },
   { GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT, "GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT" },
   { GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER, "GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER" },
   { GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER, "GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER" },
   { GL_FRAMEBUFFER_UNSUPPORTED, "GL_FRAMEBUFFER_UNSUPPORTED" },
   { GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE, "GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE" }
};
